Added the Chinese localization home page
servo/servo.org_2014-2020 pull request #37
Opened 2016-10-30 13:32 UTC by 3442853561

Added the Chinese localization home page

2016-10-30 14:03 UTC, Manishearth commented
r? @kichjang @shinglyu (not sure if either of you can read simplified)

2016-10-30 19:17 UTC, KiChjang requested changes
大致上沒有什麼大問題，而且翻譯得相當好，有勞您用心辦工！@shinglyu可能有更多建議。

2016-10-30 19:17 UTC, KiChjang commented on index(zh-CN).html
> +                <p> Servo 目前支持 Linux、OSX、Windows、安卓和 Gonk（Firefox OS）。</p>
咱們好像已經不再支持Gonk了，可否改寫一下？

2016-10-30 19:17 UTC, KiChjang commented on index(zh-CN).html
> +            <h3>准备工作</h3>
準備工作有點兒怪怪的，《系統所需》或者更恰當。

2016-10-30 19:17 UTC, KiChjang commented on index(zh-CN).html
> +            <p>对 Servo 或其依赖关系的贡献应该以 GitHub pull 的形式提交。 每个 pull 请求将由核心贡献者（有权限修补程序的人员）审核，合并到主分支中或给出反馈，以获取所需的更改。 所有贡献应遵循此形式，包括来自核心贡献者的贡献。
GitHub Pull Request

2016-10-30 19:17 UTC, KiChjang commented on index(zh-CN).html
> +            <p>如果您在找那些显而易见的漏洞，请查看 GitHub 上
這裏缺乏了E-Easy容易收復的意思。

2016-10-30 19:17 UTC, KiChjang commented on index(zh-CN).html
> +				您也可以在 irc.mozilla.org的 #servo 上要求审核 。
這裏或者可以加上我和@shinglyu的名字，以便懂漢語的貢獻者尋求拹助。

2016-10-30 19:17 UTC, KiChjang commented on index.html
> +        <a href="/index(zh-CN).html">简体中文</a>
rust-lang.org 本土化網頁的URL是`/zh-CN/index.html`，跟隨它們的格式或者會好一些，而且URL不太適宜含有括號。

2016-10-30 22:29 UTC, notriddle commented
Is 16.10.30.21.28 really a good commit message?

2016-10-31 00:33 UTC, 3442853561 commented
@notriddle there is some little bugs I will fix it today.

2016-10-31 00:34 UTC, 3442853561 commented on index.html
> +        <a href="/index(zh-CN).html">简体中文</a>
非常感谢您的建议，我今天会修复这些问题

2016-10-31 04:05 UTC, 3442853561 commented
@KiChjang I completed the localization.

2016-10-31 13:17 UTC, jdm commented
FWIW, https://github.com/jdm/asknot/ uses https://github.com/fabi1cazenave/webL10n, which then gives us localized string files: https://github.com/jdm/asknot/blob/master/locales/zh-CN.ini

2016-10-31 16:38 UTC, 3442853561 commented
@jdm I'm log in,https://support.mozilla.org/zh-CN/user/3442853561

2016-11-01 00:11 UTC, shinglyu commented
Sorry I might be a little bit late to give feedbacks (it was national holiday yesterday), but I did found some nit, you can either fix it or consider giving a followup PR.

2016-11-01 00:24 UTC, shinglyu reviewed
感謝您的貢獻 (您也同時有幫忙 Rust 語言中文化對吧?) 如果已經準備 merge 了您可以考慮之後再上一個 PR 修正這些錯誤，或是您願意現在一起修掉我也會很感激！

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +            <p class='info'>由Mozilla赞助并由全新的系统级编程语言 <a href='https://www.rust-lang.org'>Rust</a>,
最好在 Mozilla 與中文字之間留一個空白

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +            <h3>构建<</h3>
多餘的 "<"

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +            <p>如果您在找那些显而易见的漏洞，请查看 GitHub 上
這邊並不只是顯而易見，而且是強調對於初學者來說非常簡單的漏洞

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +			<a href="https://github.com/servo/servo/labels/E-easy">E-Easy 的 issue 标签</a> 。 （因为 E-Easy 更适于接收这些漏洞的报告）
"（因为 E-Easy 更适于接收这些漏洞的报告）" 抱歉，這句我不太理解?

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +            <p>有关如何开始使用 Servo 的详细信息，请参阅
"開始修改" 可能好一點

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +            <h3>Pull 请求清单</h3>
"檢查清單" 會不會比 "清單" 明確一點?

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +                <li>为新功能或修复错误添加相关测试。对于DOM的修改，通常需要一个Web平台测试、布局及反复测试。有关详细信息，请参阅
Web 一字旁請加空白

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +                <li>为新功能或修复错误添加相关测试。对于DOM的修改，通常需要一个Web平台测试、布局及反复测试。有关详细信息，请参阅
如果我理解無誤，原文應該是 "DOM 的修改通常需要一個 Web 平台測試；布局的修改需要一個參考測試 (reftest)"

2016-11-01 00:24 UTC, shinglyu commented on zh-CN/index.html
> +                <li>请不要将子模块更新放在您的pull请求中，除非它们影响提交。
pull 前後請加空白

2016-11-01 05:08 UTC, KiChjang commented on zh-CN/index.html
> +            <h3>Pull 请求清单</h3>
其實Pull Request 是否專有名詞? 譯為《Pull 請求》好像不對...

2016-11-03 09:06 UTC, 3442853561 commented
完成了修改。
PS:我的确也在帮助 Rust 完成本土化。

2016-11-08 15:13 UTC, 3442853561 commented
@KiChjang @shinglyu

2016-11-10 06:07 UTC, shinglyu commented
您方便把四個 commit 壓 (squash) 成一個嗎? 詳細方法可以參考[這篇](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) 另外請在壓完的 commit 中寫比較敘述性的 commit message, 例如 "Added zh-CN translation for the homepage" 完成後我們就可以 merge 了。感謝您的細心貢獻。

2016-11-12 03:23 UTC, 3442853561 commented
#38

2016-11-12 03:23 UTC, closed without merging