Added the Japanese translation for homepage. (Re PR)
servo/servo.org_2014-2020 pull request #60
Opened 2018-02-05 15:18 UTC by hikai

Added the Japanese translation for homepage. again PR.

I made a mistake and did it again. I'm sorry.
(Rebase is too hard.)

Thank you for @saneyuki for review!

2018-02-06 04:39 UTC, tetsuharuohzeki requested changes
@hikai  Thank you for your response!

I reviewed your updated patch. 

- I find more nice phrase at some points. They are my mistaken review in https://github.com/servo/servo.org/pull/58. I'm sorry.
- I find some miss-spells. Please fix them.

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          Servoプロジェクトは、経験が豊富な開発者から初心者まで、多くの皆さんによる開発への参加を受け入れます。
> 多くの皆さんによる開発への参加を受け入れます。

多くの皆さんによる開発への参加を歓迎しています。

would be more nice.

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          この取り組みに参加するにはページの末尾に書かれたリンクを参照してください。
> ページの末尾に書かれたリンクを

ページの末尾に記載されたリンクを

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          <a href="https://www.rust-lang.org/conduct.html">Rust 行動規範</a>に
> Rust 行動規範

Rustの行動規範

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          また、<a href="https://lists.mozilla.org/listinfo/dev-servo">開発メールリグリスト</a>でも議論が行われており、自由に参加できます。
> 開発メールリグリスト

開発メーリングリスト

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          <a href="https://github.com/servo/servo/labels/E-easy">E-Easy issue タグ</a>を
> E-Easy issue タグ

E-Easy ラベル

2018-02-06 04:39 UTC, saneyuki commented on ja-JP/index.html
> +          しかし、生成されたバイナリの動作は非常に遅いです。
> 非常に遅いです

非常に低速なことに注意してください。

would be more nice.

2018-02-11 10:30 UTC, hikai commented
Sorry, I late to commit because so busy.
Is this the right way to do a commit squash?

2018-02-12 16:09 UTC, jdm commented
Looks great. Thanks!

2018-02-12 17:31 UTC, tetsuharuohzeki approved these changes

2018-02-12 17:36 UTC, saneyuki commented
I feel this translation is good.

-------------------

@hikai 

> Sorry, I late to commit because so busy.
> Is this the right way to do a commit squash?

No problem!
Yes, squash is the right wary. Thank YOU!

-------------------

@jdm 

Could you review this pull request for the technical aspect?
I can review the translation feeling. But I'm not sure about this repository.

2018-02-12 17:57 UTC, jdm commented
Thanks for reviewing the language changes @saneyuki!

2018-02-12 17:57 UTC, merged